import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

import Navbar from "@/components/Navbar";
import Providers from "@/components/providers/index";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
   params,
}: {
   children: React.ReactNode;
   params: {
      locale: string;
   };
}) {
   return (
      <html lang={params.locale}>
         <body className="min-h-screen">
            <Providers>
               <Navbar />
               {children}
            </Providers>
         </body>
      </html>
   );
}
